configured_endpoints: 81
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mg-web%2Ftaggy-c79bf851b43e7a6befb0695b0ec1f283fa0ab977cba7e455a6ef245ad5f8e8ea.yml
openapi_spec_hash: a9d77bdcedee823e840440b0e4a8e393
config_hash: bca82244a63fb9aaefa5c80b6d77f1ff
